---
# Site navigation
nav:
  - Welcome: README.md
  - Prof. Dr. Fassnacht:
      - QGIS:
          - Getting to know the graphical user interface: ./qgis/01-GUI.md
          - Loading and visualizing Shapefiles / Vector data: ./qgis/02-vector-data.md
          - Loading and visualizing raster data: ./qgis/03-raster-data.md
          - Useful general tools: ./qgis/04-general-tools.md
          - Basic vector processing: ./qgis/05-digitizing.md
          - Spatial and semantic selection: ./qgis/06-selections.md
          - Working with elevation raster datasets: ./qgis/07-elevation.md
          - Making a map: ./qgis/08-map-making.md
          - Spatial interpolation: ./qgis/09-spatial-interpolation.md
      - R:
          - Getting started with processing laserscanning data: ./1_Laserscanning_lidR/1_Laserscanning_lidR.md
          - Classification of tree species using hyperspectral data: ./treespeciesclassification/treespeciesclassification.md
          - Analysing time series with BFAST and NPPHEN: ./BFAST/BFAST.md
          - Calculation of Landscape Metrics from a Land-cover raster map: ./landscape_metrics/landscape_metrics.md
          - Calculating semivariograms and Autocorrelograms: ./spatial_autocorrelation/spatial_autocorrelation.md
      - GEE:
          - Preparing time series data stacks: ./MSRS_1_GEE_basics/MSRS_1_GEE_basics.md
          - Preparing annual time series data stacks and conducting time series analysis: ./MSRS_1_GEE_basics2/MSRS_1_GEE_basics2.md
      - SNAP:
          - Download of Landsat and Sentinel satellite images: ./planetary-sciences/01-download-ls-and-s2.md
  - GIS:
      - R:
          - Introduction: ./gis/introduction.md
          - Visualization and Map: ./gis/visualization-and-map.md
          - Attributes, Filters and Metadata: ./gis/attributes-filters-and-metadata.md
          - Geoprocesing and reference and coordinate systems: ./gis/geoprocesing-and-reference-and-coordinate-systems.md
  - Other:
      - School internship: ./schuelerpraktikum/handout.md
      
      
      
      
# Site information
site_name: REMOTE SENSING AND GEOINFORMATICS
copyright: Copyright &copy; CC-BY-SA-4.0 license - Freie Universität Berlin Institute of Geographical Sciences Remote Sensing and Geoinformatics




# Repository connection
repo_name: Remote-Sensing-at-FU-Berlin.github.io
repo_url: https://github.com/Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io/
edit_uri: tree/main/docs




# Design and features
theme:
  favicon: assets/favicon.png
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
  name: material
  language: en
  palette:
    primary: white
    accent: light green
extra:
  generator: false




# Markdown plugins
markdown_extensions:

  # Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Inhaltsverzeichnis
      permalink_title: Link zu dieser Sektion
  - tables

  # Python Markdown
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde




# Javascript plugins
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js




# Other plugins
plugins:
  - search
  - glightbox

