site_name: Fernerkundung und Geoinformatik

nav:
    - Inhaltsverzeichnis: 'index.md'
    - Geographische Informationssysteme: './Geographische Informationssysteme'

theme:
  name: material
  language: de 
  palette:
    primary: light green
    accent: light green
