site_name: Fernerkundung und Geoinformatik

nav:
    - Home: 'index.md'
    - Geographische Informationssysteme:
        - '1. Einführung ArcGIS': '1_einfuerung_in_arcmap.md'
        - '2. Kartenerstellung': '2_visualisierung_von_daten_und_kartenerstellung.md'
        - '3. Abfragen': '3_abfragen.md'
        - '4. Digitalisierung 1 + 2': '4_digitalisierung.md'
        - '5. Geoprozessierung und Projektionen': '5_geoprozessierung_und_projektionen.md'
        - '6. Interpolationen und Höhenmodelle': '6_interpolationen_und_hoehenmodelle.md'
        - '7. Abschlussaufgabe': '7_abschlussaufgabe.md'

theme:
  name: material
  language: de 
  palette:
    primary: light green
    accent: light green
