site_name: Fernerkundung und Geoinformatik

nav:
    - Home: 'index.md'
    - Geographische Informationssysteme:
        - '01 Einführung ArcGIS': '1_einfuerung_in_arcmap.md'
        - '02 Kartenerstellung': '2_visualisierung_von_daten_und_kartenerstellung.md'

theme:
  name: material
  language: de 
  palette:
    primary: light green
    accent: light green
