site_name: Fernerkundung und Geoinformatik

nav:
    
    - Geo. Informationssysteme:
        - ArcGis Pro:
            - 'Bildinterpretation mit Google Earth': './arcgis-tutorials/bildinterpretation_mit_google_earth.md'
            - 'Einführung ArcGIS': './arcgis-tutorials/einfuerung_in_arcmap.md'
            - 'Kartenerstellung': './arcgis-tutorials/visualisierung_von_daten_und_kartenerstellung.md'
            - 'Abfragen': './arcgis-tutorials/abfragen.md'
            - 'Digitalisierung': './arcgis-tutorials/digitalisierung.md'
            - 'Geoprozessierung und Projektionen': './arcgis-tutorials/geoprozessierung_und_projektionen.md'
            - 'Interpolationen und Höhenmodelle': './arcgis-tutorials/interpolationen_und_hoehenmodelle.md'
            - 'Abschlussaufgabe': './arcgis-tutorials/abschlussaufgabe.md'
        - QGIS:
            - 'GUI': './qgis-tutorials/01-GUI.md'
            - 'Vector Data': './qgis-tutorials/02-vector-data.md'
            - 'Raster Data': './qgis-tutorials/03-raster-data.md'
            - 'General Tools': './qgis-tutorials/04-general-tools.md'
            - 'Digitizing': './qgis-tutorials/05-digitizing.md'
            - 'Selections': './qgis-tutorials/06-selections.md'
            - 'Elevation': './qgis-tutorials/07-elevation.md'
            - 'Map Making': './qgis-tutorials/08-map-making.md'
            - 'Spatial Interpolation': './qgis-tutorials/09-spatial-interpolation.md'
    - Fern. und digitale Bildverarbeitung:
        - 'Google Earth': 'google_earth.md'
        - 'Erdas': 'erdas.md'
        - 'Profile': 'profile.md'
        - 'Kontrast': 'kontrast.md'
        - 'Geometrische Korrektur': 'geometrische_korrektur.md'
        - 'Vegetationsindizes': 'vegetationsindizes.md'
        - 'Datenraumtransformationen': 'datenraumtransformationen.md'
        - 'Unüberwachte Klassifikation': 'unueberwachte_klassifikation.md'
        - 'Überwachte Klassifikation': 'ueberwachte_klassifikation.md'
        - 'Validierung': 'Validierung.md'
        - 'Abschlussaufgabe': 'abschlussaufgabe.md'
    - Regionale Themen der Fern.:
        - 'Test': 'test.md'
    - Speziele Themen der Fern.:
        - 'Test': 'test.md'
    - Projektbezogenes Arbeiten:
        - 'Test': 'test.md'
    - Planetary Sciences:
        - 'Download': './planetary-sciences-tutorials/01-download-ls-and-s2.md'

copyright: Copyright - 2023 Fabian Faßnacht & Anika Sieber
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - navigation.footer
    
  logo: assets/logo.png
  name: material
  language: de 
  palette:
    primary: white
    accent: light green


extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html  