---
site_name: Fernerkundung und Geoinformatik
nav:
  - Geo. Informationssysteme:
      - ArcGis Pro:
          - Bildinterpretation mit Google Earth: ./gis/arcgispro/bildinterpretation_mit_google_earth.md
      - QGIS:
          - Getting to know the graphical user interface: ./gis/qgis/01-GUI.md
          - Loading and visualizing Shapefiles / Vector data: ./gis/qgis/02-vector-data.md
          - Loading and visualizing raster data: ./gis/qgis/03-raster-data.md
          - Useful general tools: ./gis/qgis/04-general-tools.md
          - Basic vector processing: ./gis/qgis/05-digitizing.md
          - Spatial and semantic selection: ./gis/qgis/06-selections.md
          - Working with elevation raster datasets: ./gis/qgis/07-elevation.md
          - Making a map: ./gis/qgis/08-map-making.md
          - Spatial interpolation: ./gis/qgis/09-spatial-interpolation.md
  - Planetary Sciences:
      - Download of Landsat and Sentinel satellite images: ./planetary-sciences/01-download-ls-and-s2.md

copyright: CC-BY-SA-4.0 license - FU-Berlin Fernerkundung und Geoinformatik

repo_url: https://github.com/Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io/
edit_uri: tree/main/docs


repo_name: Remote-Sensing-at-FU-Berlin.github.io

theme:
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - search.highlight
    - content.action.edit
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
  logo: logo.png
  name: material
  language: de
  palette:
    primary: white
    accent: light green
extra:
  generator: false
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
