name: mkdocs_build 

on:
  schedule:
    - cron: '0 1 * * */1'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/*'
      - 'mkdocs.yml'
      - '.gitmodules'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
          token: ${{ secrets.PAT }}
          
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - name: Git submodule update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      
      - name: commit update
        run: |
          git config --global user.name ${{ secrets.USER }}
          git config --global user.email ${{ secrets.EMAIL }}
          git commit -am "automatic updated submodule references" && git push || echo "No changes to commit"
      
      - name: install plugins
        run: pip install \
              mkdocs-material \
              mkdocs-glightbox \
      
      - name: build website
        run: mkdocs gh-deploy --force
