name: mkdocs_build 

on:
  #schedule:
  #  - cron: '0 1 * * */1'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.gitmodules'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - name: install plugins
        run: pip install \
              mkdocs-material \
              mkdocs-glightbox \
      
      - name: build website
        run: mkdocs gh-deploy --force
